### PR TITLE
feat: analytics

### PR DESCRIPTION
**Pull request by tomassasovsky**
This PR adds tracking using Google Analytics.

### CODE REVIEW

**Review by NazarenoCavazzon — APPROVED** [review]
lgtm

**Review by jorger5 — APPROVED** [review]
Great job!

**Comment by tomassasovsky** [comment]
Closing due to unsufficient support from Google Analytics for our solution.

**Comment by NazarenoCavazzon** [comment]
that phrase didn't age well, say sorry to our god google

**Comment by tomassasovsky** [comment]
Reopening as we got google analytics working!

**Pull request merged**
